#!/bin/bash
#
# a simple usage function framework which will output basic program
# information and call a hook function to provide further details to the
# user.
#
#  hook function name is  [programName]Usage 
#    where programName is stored in prog[name]
#    and  can be overridden with usage[detail] variable
#

# prepare usage descriptor array
declare -A usage

function usage() {
    cat <<EndOfFragment
${prog[name]} version ${usage[version]:-0.0.1}
${usage[description]:-"a simple but brief statement of purpose"}

EndOfFragment

    # call usage detail hook function
    ${usage[detail]:-${prog[name]}Usage} "$@"
}
